### ISSUE TITLE
Request: Add ability to select Dirac EQ Preset with service call

### ISSUE THREAD

**Issue by JoshMcWilson** [peteS-UK/emotiva#3]
I was wondering if it would be possible to add an option to the Emotiva.send_command to select one of the Dirac EQ presets? 

Gen 3 processors have 3 Dirac slots and one User slot (manual EQ) under the EQ options. Being able to switch between the Dirac slots quickly has been one of my biggest feature requests for these processors so that would be great. 

If you need more info let me know. And if it’s not possible I totally understand.

**Comment by JoshMcWilson** [comment]
Ok, not sure how I missed it before but there is a Dirac option in the service call list. 

I tried it out but it was switching different speaker presets as well when calling it. 

How do I determine what to enter into the Command Value to select each preset?

**Comment by peteS-UK** [comment]
@JoshMcWilson The problem is that the API doc doesn't list the new Dirac modes - just the single dirac mode that existed for the XMC and the 2 "speaker presets", which I guess are the equivelent of manual.

Turn on debug logging again, and switch between the dirac modes, and the manual one.  Let's see what debug the processor spits out to see if that might give us a clue if there's a command in there.  It's entirely possible sadly that emo haven't updated the API to support changing the dirac mode, but let's have a look.

**Comment by peteS-UK** [comment]
This from the RMC dirac manual

_The current version offers two independent Speaker Presets, each of which can store up to three Dirac Live room correction profiles, along with one manual EQ profile. Various menu options allow you to choose a default profile, associate particular profiles with specific inputs, or manually switch between profiles on the fly._

The API doc, which was written for the XMC-1, only has 3 Speaker Presets - one Dirac and 2 manual - and no profiles within them.  I have the latest doc, but let's see if the debug tells us anything.  Else, we can ask emotiva and see if they tells us anything

**Comment by peteS-UK** [comment]
Actually, add speaker_preset as an additional notification before you gather the logs - in the configure option we used to add back to get it setup originally.  I don't track that status at the moment, and it might contain something useful.

**Comment by JoshMcWilson** [comment]
I'm not sure if there's something I'm missing, or maybe the API doesn't support the Dirac modes, but the debug logs don't show anything when I step through the dirac presets on the processor with debug enabled. Looking at the logs for the time where I did it there is nothing there unfortunately... 

Is it possible I need to restart HA or something before running a new debug? Doubt that would be the case but not sure....

**Comment by peteS-UK** [comment]
No, that was my concern.  It seems likely that the API hasn't been updated for the XMC-2/RMC preset structure, so it's not sending out any subscription notices.  I thought this might be the case since there's nothing in the doc, but it was worth a try.  I'll send Emo a mail and ask them, but don't hold your breath.

**Comment by peteS-UK** [comment]
OK, the good news is that I heard back from Emo really quickly.  The bad news is that they're not doing anything with the current generation of the API since they're working on the next gen of processors now, so aren't interested in the current ones.  I think the only was you'll be able to do it is to build a macro from multiple key presses I'm afraid.

**Comment by JoshMcWilson** [comment]
That's what I was afraid of, thanks for checking with them though. It's unfortunate that Emotiva does not plan to continue working on the current gen processors, and the fact that they didn't update the API for them to include these features. Oh well, I appreciate you looking into this. 

Regardless of this, the integration you've built is amazing! It does so much more than I expected based on my experience with the Emotiva processor, I assumed the API would be really limited. This does far more than I expected, and works great. Thanks!

**Comment by peteS-UK** [comment]
Yes, it's a shame.  There are some things which just don't work in the API from XMC-1 days (e.g. Dimming just pops up the banner but doesn't do anything) which they never fixed, so I guess I'm not overly surprised.

I was surprised when I looked originally that there wasn't any integration for Emotiva around tbh.  I would have thought that there would be a decent cross over of people who make the non-standard choice of Emotiva vs. just buying the normal stuff who also chose HA, but it seems not, and hence I had to write this for my own setup.  Trouble is, once you start, you feel compelled to write them for anything you have that isn't yet integrated....  I have one old Sony Blu-ray player in the gym which doesn't work with any of the existing integrations I can find, has no published API and I've wasted far too much time trying to figure it out.
